### ISSUE TITLE
Allow passing log files directly instead of scanning

### ISSUE THREAD

**Issue by ghost** [soypat/gitaligned#6]
Hi there,

I want to try building a GUI for `gitaligned` to run against arbitrary projects for fun. However, cloning entire repositories just for their logs seems a little heavy-handed (even with the `--bare` flag). It would be nice if I could, for example, pull a list of commits from the GitHub API, massage it into the `git log` format and pass it to the program.

As far as I can tell, this would only require to expose this function on the command line:
https://github.com/soypat/gitaligned/blob/a37e99043f591cfad60d04dc6e329a00d632f172/gitscan.go#L92

Hope you consider it. Thank you.

**Comment by soypat** [comment]
I like the idea. I'll see what I can do

**Comment by ghost** [comment]
Thank you kindly.
